package com.peycash.common;

public enum StatusAmounts {
	DAYLI_LIMIT_EXCEED_BY_SENDER, DAYLI_LIMIT_EXCEED_BY_RECEIVER,
	MONTHLY_LIMIT_EXCEED_BY_SENDER, MONTHLY_LIMIT_EXCEED_BY_RECEIVER,
	STATUS_OK;
}
